name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalando Dependencias
        run: npm install
  test:
    steps:
      - name: Ejecutando Test Coverage
        run: npm run test:coverage

      - name: Ejectando Tests
        run: npm run test
