name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-y-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalando Dependencias
        run: npm install

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ejecutando Tests
        run: npm run test

      - name: Ejecutando Test Coverage
        run: npm run test:coverage
