name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-y-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Intalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalando dependencias
        run: npm install

      - name: Inicializando Tests
        run: npm test --

      - name: Inicializando Test Coverege
        run: npm test -- --coverage
